<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('test', function(){
  $products = \App\Model\Product::where('stock', '>', 0)
                            ->orderByRaw('RAND()')
                            ->take(3)
                            ->get();
                            dd($products);
                          });


// generated by hesto/multi-auth

Route::group(['prefix' => 'admin'], function () {
  Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
  Route::post('/login', 'AdminAuth\LoginController@login');
  Route::post('/logout', 'AdminAuth\LoginController@logout');

  Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm');
  Route::post('/register', 'AdminAuth\RegisterController@register');

  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');
  Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');

  //change password
  Route::get('/change-password', 'Admin\HomeController@getChangePassword')->name('admin.change-password');
  Route::post('/change-password', 'Admin\HomeController@postChangePassword');
  
  Route::get('', 'Admin\HomeController@showHome')->name('admin');
});

Route::resource('admin/product', 'Admin\ProductController');
Route::get('admin/order', 'Admin\OrderController@index')->name('order.index');
